#!/bin/zsh


# base-devel, libxft - build dependency for some SL programs
# xorg-xinput - enable/disable devices like mouse pad
# xf86-video-intel - required by xbaklight in x220
# fprintd - Thinkpad fingerprint authentication
# xf86-input-wacom - Remaping wacom express keys
# acpilight is a replacement for not working xorg-backlight in t470, both provides xbacklight executable

sudo pacman --noconfirm --needed -S \
	base-devel arch-install-scripts \
	xclip imagemagick \
	man-pages man-db \
	libxft \
	terminus-font noto-fonts{,-emoji} \
	xf86-input-wacom \
	xorg-{server,xinit,xsetroot} \
	acpilight \
	mpv youtube-dl \
	pulseaudio pulseaudio-alsa pavucontrol \
	slock sxiv dzen2 \
	rclone \
	syncthing \
	transmission-cli \
	nitrogen \
	sxhkd \
	redshift \
	flameshot \
	sdcv \
	fzf \
	beep \
	neofetch \
	zip unzip tar \
	zathura zathura-djvu zathura-pdf-mupdf \
	pcmanfm gvfs-mtp ffmpegthumbnailer xterm \
	ntfs-3g \
	docker flatapk \ 
	tlp tlp-rdw acpi_call-lts \
	smartmontools 

cd $HOME/code 
for i (dwm st dmenu)
do
    if ! [ -d $i ]
    then
        git clone "https://github.com/albertshaji/${i}.git"
    fi
    sudo make -C $i clean install
done


cd
echo "exec dwm" >.xinitrc
echo "exec startx" >.zprofile
