#!/bin/zsh

KERNEL=linux-lts
USER=alby
PASS=0000
HOSTNAME=arch
TIMEZONE=Asia/Kolkata
DISK=/dev/sda

#TARGET='--removable' #uncomment to install on pendrive
#pacman -S arch-install-scripts #If not via iso

set -e
test $EUID -eq 0

timedatectl set-ntp true

yes | mkfs.fat -F32  ${DISK}1
mkswap ${DISK}2
yes | mkfs.ext4 -c ${DISK}3

mount ${DISK}3 /mnt
mkdir -p /mnt/{boot/efi,home}
mount ${DISK}1 /mnt/boot/efi
swapon ${DISK}2
mount ${DISK}4 /mnt/home

pacstrap /mnt base base-devel \
    $KERNEL linux-firmware sof-firmware \
    neovim zsh git \
    grub efibootmgr \
    networkmanager \
    intel-ucode

genfstab -U /mnt >/mnt/etc/fstab

cd /mnt/home
if [[ -d $USER ]]
then
    cd $user
    MY=(. .. audio code dl dox dt phone pix video art www .gnupg .password-store .stardict .aur)

    LS=($(ls -a))

    CO=($(printf "%s\n" $MY $LS | sort | uniq -d))
    DF=($(printf "%s\n" $CO $LS | sort | uniq -u))

    # archive the unwanted 
    TO=$(date +'%b%d')
    mkdir $TO
    mv $DF $TO

    # create if they don't exist
    NO=($(printf "%s\n" $MY $CO | sort | uniq -u))
    mkdir $NO
fi

cat <<EOF | arch-chroot /mnt
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc

echo "en_US.UTF-8 UTF-8" >/etc/locale.gen
echo "en_US ISO-8859-1" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo $HOSTNAME >/etc/hostname
echo "127.0.0.1 localhost" >/etc/hosts

grub-install $DISK $TARGET
sed -i "/GRUB_TIMEOUT_STYLE/c\GRUB_TIMEOUT_STYLE=hidden" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager

useradd -m -g wheel -s /bin/zsh $USER
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

echo "$USER:$PASS" | chpasswd
echo "root:$PASS" | chpasswd

mkdir -p /etc/systemd/system/getty@tty1.service.d
echo "[Service]
ExecStart=
ExecStart=-/usr/bin/agetty -n -o $USER --noclear %I \$TERM" >/etc/systemd/system/getty@tty1.service.d/override.conf
EOF
