#!/bin/zsh

set -e 

if [[ $EUID -eq 0 ]]; then
    echo "Don't run as root!"
    exit 1
fi


# conf loop
cd $HOME/code/design/conf

count=0 
total=$(ls | wc -l)
echo "Total: $total\n"

for i in * 
do 
	count=$((count + 1))

	if pacman -Q $(head -n1 $i | cut -c 3-) &>/dev/null
	then

		j=$(sed -n 2p $i | cut -c 3-)

		if [[ $(echo $j | cut -c 1) = '/' ]]
		then
			sudo mkdir -pv $(dirname $j) 
			sudo cp -v $i $j 
		else 
			mkdir -pv $(dirname $j) 
			cp -v $i $HOME/$j 
		fi 
		echo "$count/$total done\n"

	else 
		echo "$count/$total $i skipped\n"
	fi
done 



# run loop 
cd ../run 

count=0 
total=$(ls | wc -l)
echo "Total: $total\n"

for i in *
do 
	count=$((count + 1))

	if pacman -Q $i &>/dev/null
	then
		echo "$count/$total $i ran\n"
        	./$i
	else 

		echo "$count/$total $i skipped\n"
    	fi
done
