#!/bin/zsh

set -e 

if [[ $EUID -eq 0 ]]; then
    echo "Don't run as root!"
    exit 1
fi

# conf loop
cd $HOME/code/design/conf

count=0 
total=$(ls | wc -l)
echo "Total: $total\n"

for i in * 
do 
	count=$((count + 1))

	app=($(head -n1 $i | cut -c 3-))
	
	# an expection 
	if [[ $i = 'sxivkey' ]] 
	then 
		app='sxiv'
		echo "Here is an expection"
	fi

	if pacman -Q $app &>/dev/null
	then

		j=$(sed -n 2p $i | cut -c 3-)

		if [[ $(echo $j | cut -c 1) = '/' ]]
		then
			if [[ $1 = '--save' ]]
			then 
				cp -v $j $i
			else
				sudo mkdir -pv $(dirname $j) 
				sudo cp -v $i $j 
			fi
		else 
			if [[ $1 = '--save' ]]
			then
				cp -v $HOME/$j $i
			else
				mkdir -pv $HOME/$(dirname $j) 
				cp -v $i $HOME/$j 
			fi
		fi 
		echo "$count/$total done\n"

	else 
		echo "$count/$total $i skipped\n"
	fi
done 

if [[ $1 = '--save' ]]
then exit 
fi

# run loop 
cd ../run 

count=0 
total=$(ls | wc -l)
echo "Total: $total\n"

for i in *
do 
	count=$((count + 1))

	if pacman -Q $i &>/dev/null
	then
		echo "$count/$total $i ran\n"
        	./$i
	else 

		echo "$count/$total $i skipped\n"
    	fi
done
