# xorg-xinit
# .xinitrc

nitrogen --set-zoom-fill pix/.wallpaper
xbacklight -set 7
xrdb .Xresources

# vim like hjkl navigation with capslock
xmodmap -e "keycode 66 = Mode_switch"
xmodmap -e "add mod1 = Menu"
xmodmap -e "keysym h = h H Left"
xmodmap -e "keysym l = l L Right"
xmodmap -e "keysym k = k K Up"
xmodmap -e "keysym j = j J Down"

# mouse acceleration
xset m 4 0

# keyboard repeat delay and rate
xset r rate 300 50

dwm-status
battery-check
temperature-check
weather-update
wifi-inactive &
sxhkd &
redshift &
flameshot &
xautolock -time 15 -locker slock &
# start searx 

exec dbus-launch dwm
